# Generated by Django 4.2.2 on 2023-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
